---
- hosts: localhost
  become: yes
  roles:
    - role: geerlingguy.apache

    - role: geerlingguy.php

    - role: geerlingguy.mysql
      mysql_root_password: test
      mysql_root_password_update: yes

    - role: community.zabbix.zabbix_server
      zabbix_server_database: mysql
      zabbix_server_mysql_login_user: root
      zabbix_server_mysql_login_password: test
      zabbix_db_type_long: mysql
      zabbix_server_dbport: 3306

    - role: community.zabbix.zabbix_web
      zabbix_server_database: mysql
      zabbix_db_type_long: mysql
      zabbix_server_dbport: 3306

    - role: community.zabbix.zabbix_agent
      zabbix_agent_server: localhost,10.128.0.16
      zabbix_api_login_user: Admin
      zabbix_api_login_pass: zabbix
      zabbix_api_create_hostgroup: true
      zabbix_api_create_hosts: true
      zabbix_agent_become_on_localhost: false
      zabbix_agent_host_state: present
      zabbix_host_groups:
        - Linux Servers
      zabbix_agent_link_templates:
        - Linux by Zabbix agent
        - Apache by HTTP
